UPDATE [dbo].LanguageLocalizationMap SET Value='Institution financière associée: (LLC seulement)' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=625
UPDATE [dbo].LanguageLocalizationMap SET Value='Votre demande ne peut pas être complétée. Pour obtenir de l''aide,veuillez envoyer un courriel au LLCSupport@FCT.ca ou appelez-nous au 1.877.929.0990' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1259
UPDATE [dbo].LanguageLocalizationMap SET Value='Prix d''une assurance titres résidentielle pour' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1460
UPDATE [dbo].LanguageLocalizationMap SET Value='Pour chaque police prêteur supplémentaire' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1498
UPDATE [dbo].LanguageLocalizationMap SET Value='Ajoutez 50,00 $ par transaction.' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1499
UPDATE [dbo].LanguageLocalizationMap SET Value='Couverture post-police si une personne construit une structure qui empiète sur le terrain du propriétaire résidentiel.' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1511
UPDATE [dbo].LanguageLocalizationMap SET Value='Compte en fidéicommis pour :' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1686
UPDATE [dbo].LanguageLocalizationMap SET Value='(Veuillez sélectionner tous les types applicables)' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1687
UPDATE [dbo].LanguageLocalizationMap SET Value='LLC' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1688
UPDATE [dbo].LanguageLocalizationMap SET Value='EasyFund' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1689
UPDATE [dbo].LanguageLocalizationMap SET Value='Adresse de la banque :' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1691
UPDATE [dbo].LanguageLocalizationMap SET Value='L''adresse de la banque est obligatoire.' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1693
UPDATE [dbo].LanguageLocalizationMap SET Value='Ville de la banque:' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1694
UPDATE [dbo].LanguageLocalizationMap SET Value='La ville de la banque est obligatoire.' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1695
UPDATE [dbo].LanguageLocalizationMap SET Value='Province de la banque:' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1696
UPDATE [dbo].LanguageLocalizationMap SET Value='La province de la banque est obligatoire.' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1697
UPDATE [dbo].LanguageLocalizationMap SET Value='Code postal de la banque:' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1698
UPDATE [dbo].LanguageLocalizationMap SET Value='Format valide: <b>A1A 1A1</b>' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1699
UPDATE [dbo].LanguageLocalizationMap SET Value='Veuillez inscrire un code postal valide.' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1701
UPDATE [dbo].LanguageLocalizationMap SET Value='Type' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1702
UPDATE [dbo].LanguageLocalizationMap SET Value='État de la vérification.' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1703
UPDATE [dbo].LanguageLocalizationMap SET Value='Si ce n''est pas encore fait, veuillez envoyer aux opérations par courriel un chèque annulé <BR \> à solicitorvoid@fct.ca ou par télécopieur au 1-855-318-6041 afin d''activer votre compte en fidéicommis.' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1704
UPDATE [dbo].LanguageLocalizationMap SET Value='Vous tentez d''accéder au Portail de la Solution de gestion d''hypothèques ou de l''assuance titres résidentielle? <a href=''{0}'' target="_blank">Cliquez ici</a>.' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1705
UPDATE [dbo].LanguageLocalizationMap SET Value='Pour accéder au Portail LLC <a href=''{0}'' target="_blank">cliquez ici</a>.' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1706
UPDATE [dbo].LanguageLocalizationMap SET Value='Informations sur le compte en fidéicommis' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1707
UPDATE [dbo].LanguageLocalizationMap SET Value='Vous n''êtes actuellement pas inscrit au Portail LLC. Pour vous inscrire, veuillez communiquer avec le soutien LLC  <br/>par téléphone :905.287.2393 <br/>sans frais :1.877.929.0990<br/><br/>Les heures de service sont du lundi au vendredi de 8h à 20h, HNE <br/><br/>Si vous désirez' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1708
UPDATE [dbo].LanguageLocalizationMap SET Value='Vous n''êtes actuellement pas inscrit au Portail de Solution de gestion d''hypothèques et d''assurance titres résidentielle.<br/><br/>Pour vous inscrire à l''assurance titres résidentielle, veuillez communiquer avec nous au 1.866.804.3122.<br/><br/>Pour vous inscrire à la Solution de gestion d''hypothèques, veuillez communiquer avec nous au 1.877.929.09' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1709
UPDATE [dbo].LanguageLocalizationMap SET Value='Veuillez sélectionner au moins un produit' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1710
UPDATE [dbo].LanguageLocalizationMap SET Value='Le compte en fidéicommis a bien été effacé. <br />Pour toutes les transactions actives ou en cours, veuillez mettre à jour votre sélection de compte en fidéicommis. <br />Pour les utilisateurs LLC: s''il y a lieu, veuillez soumettre une Demande de fonds amendée. Si vous faites affaire avec la Banque TD, veuillez communiquer directement avec eux au ' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1711
UPDATE [dbo].LanguageLocalizationMap SET Value='Le compte en fidéicommis a bien été supprimé.</br> Pour toutes les transactions actives ou en attente, veuillez mettre à jour votre sélection de compte en fidéicommis.' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1712
UPDATE [dbo].LanguageLocalizationMap SET Value='Vous avez modifié l''information sur le compte en fidéicommis. </br>Pour toutes les transactions actives et en attente, veuillez mettre à jour la sélection de votre compte en fidéicommis. </br> Pour les utilisateurs LLC: Si vous transigez avec la Banque TD, veuillez communiquer avec eux directement pour les informer de tout</br> changement que vous avez fait à' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1715
UPDATE [dbo].LanguageLocalizationMap SET Value='Les changements faits ont été mis à jour avec succès.</BR>Si vous transigez avec la Banque TD, veuillez communiquer avec eux directement pour les informer de tout changement que vous avez fait sur vos coordonnées ou sur les informations de votre compte en fidéicommis.' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1716
UPDATE [dbo].LanguageLocalizationMap SET Value='Veuillez sélectionner au moins un produit' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1717
UPDATE [dbo].LanguageLocalizationMap SET Value='Vous devez accepter les modalités et stipulations de la Reconnaissance avant de pouvoir utiliser le Portail LLC. Veuillez choisir <Return to Acknowledgement> revenir à la Reconnaissance. <br/>Si vous désirez obtenir plus d''informations sur l''acceptation obligatoire des modalités' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1718
UPDATE [dbo].LanguageLocalizationMap SET Value='Des associations d''institution financière en double ont été trouvées.' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1723
UPDATE [dbo].LanguageLocalizationMap SET Value='FCT 905.287.3122 ou sans frais au 1.866.804.3122 LLC 905.287.2393 ou sans frais au 1.877.929.0990' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1725
UPDATE [dbo].LanguageLocalizationMap SET Value='Soutien au 905.287.2393 ou sans frais au 1.877.929.0990' WHERE [LanguageID]=(SELECT  [LanguageID]  FROM [dbo].[Language]  where [Name]='French') AND LocalizationID=1726
