//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.EPS.WSP.ExternalResources.Tokenizer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Tokenizer.ITokenization", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface ITokenization {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenization/Tokenize", ReplyAction="http://tempuri.org/ITokenization/TokenizeResponse")]
        string Tokenize(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenization/Tokenize", ReplyAction="http://tempuri.org/ITokenization/TokenizeResponse")]
        System.Threading.Tasks.Task<string> TokenizeAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenization/Untokenize", ReplyAction="http://tempuri.org/ITokenization/UntokenizeResponse")]
        string Untokenize(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenization/Untokenize", ReplyAction="http://tempuri.org/ITokenization/UntokenizeResponse")]
        System.Threading.Tasks.Task<string> UntokenizeAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITokenizationChannel : FCT.EPS.WSP.ExternalResources.Tokenizer.ITokenization, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenizationClient : System.ServiceModel.ClientBase<FCT.EPS.WSP.ExternalResources.Tokenizer.ITokenization>, FCT.EPS.WSP.ExternalResources.Tokenizer.ITokenization {
        
        public TokenizationClient() {
        }
        
        public TokenizationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenizationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenizationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenizationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Tokenize(string value) {
            return base.Channel.Tokenize(value);
        }
        
        public System.Threading.Tasks.Task<string> TokenizeAsync(string value) {
            return base.Channel.TokenizeAsync(value);
        }
        
        public string Untokenize(string token) {
            return base.Channel.Untokenize(token);
        }
        
        public System.Threading.Tasks.Task<string> UntokenizeAsync(string token) {
            return base.Channel.UntokenizeAsync(token);
        }
    }
}
