//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentNotificationRequest", Namespace="FCT.EPS.PaymentTrackingService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PaymentNotificationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.PaymentNotificationList PaymentNotificationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.PaymentNotificationList PaymentNotifications {
            get {
                return this.PaymentNotificationsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentNotificationsField, value) != true)) {
                    this.PaymentNotificationsField = value;
                    this.RaisePropertyChanged("PaymentNotifications");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PaymentNotificationList", Namespace="FCT.EPS.PaymentTrackingService.DataContracts", ItemName="PaymentNotification")]
    [System.SerializableAttribute()]
    public class PaymentNotificationList : System.Collections.Generic.List<FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.PaymentNotification> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentNotification", Namespace="FCT.EPS.PaymentTrackingService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PaymentNotification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.PaymentNotification.NotificationTypeType NotificationTypeField;
        
        private string PaymentReferenceNumberField;
        
        private string DisbursementRequestIDField;
        
        private System.DateTime PaymentDateTimeField;
        
        private decimal PaymentAmountField;
        
        private FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.Account PaymentOriginatorAccountField;
        
        private string PaymentOriginatorNameField;
        
        private string PaymentBatchIDField;
        
        private string PaymentBatchDescriptionField;
        
        private string AdditionalInformationField;
        
        private string PaymentStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.PaymentNotification.NotificationTypeType NotificationType {
            get {
                return this.NotificationTypeField;
            }
            set {
                if ((this.NotificationTypeField.Equals(value) != true)) {
                    this.NotificationTypeField = value;
                    this.RaisePropertyChanged("NotificationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaymentReferenceNumber {
            get {
                return this.PaymentReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentReferenceNumberField, value) != true)) {
                    this.PaymentReferenceNumberField = value;
                    this.RaisePropertyChanged("PaymentReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string DisbursementRequestID {
            get {
                return this.DisbursementRequestIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DisbursementRequestIDField, value) != true)) {
                    this.DisbursementRequestIDField = value;
                    this.RaisePropertyChanged("DisbursementRequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime PaymentDateTime {
            get {
                return this.PaymentDateTimeField;
            }
            set {
                if ((this.PaymentDateTimeField.Equals(value) != true)) {
                    this.PaymentDateTimeField = value;
                    this.RaisePropertyChanged("PaymentDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal PaymentAmount {
            get {
                return this.PaymentAmountField;
            }
            set {
                if ((this.PaymentAmountField.Equals(value) != true)) {
                    this.PaymentAmountField = value;
                    this.RaisePropertyChanged("PaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.Account PaymentOriginatorAccount {
            get {
                return this.PaymentOriginatorAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentOriginatorAccountField, value) != true)) {
                    this.PaymentOriginatorAccountField = value;
                    this.RaisePropertyChanged("PaymentOriginatorAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string PaymentOriginatorName {
            get {
                return this.PaymentOriginatorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentOriginatorNameField, value) != true)) {
                    this.PaymentOriginatorNameField = value;
                    this.RaisePropertyChanged("PaymentOriginatorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string PaymentBatchID {
            get {
                return this.PaymentBatchIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentBatchIDField, value) != true)) {
                    this.PaymentBatchIDField = value;
                    this.RaisePropertyChanged("PaymentBatchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string PaymentBatchDescription {
            get {
                return this.PaymentBatchDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentBatchDescriptionField, value) != true)) {
                    this.PaymentBatchDescriptionField = value;
                    this.RaisePropertyChanged("PaymentBatchDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string AdditionalInformation {
            get {
                return this.AdditionalInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInformationField, value) != true)) {
                    this.AdditionalInformationField = value;
                    this.RaisePropertyChanged("AdditionalInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public string PaymentStatus {
            get {
                return this.PaymentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentStatusField, value) != true)) {
                    this.PaymentStatusField = value;
                    this.RaisePropertyChanged("PaymentStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="PaymentNotification.NotificationTypeType", Namespace="FCT.EPS.PaymentTrackingService.DataContracts")]
        public enum NotificationTypeType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CreditConfirmation = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DebitConfirmation = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ChequeConfirmation = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            FCTFeeConfirmation = 3,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="FCT.EPS.PaymentTrackingService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        private string BankNumberField;
        
        private string TransitNumberField;
        
        private string AccountNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BankNumber {
            get {
                return this.BankNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNumberField, value) != true)) {
                    this.BankNumberField = value;
                    this.RaisePropertyChanged("BankNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TransitNumber {
            get {
                return this.TransitNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TransitNumberField, value) != true)) {
                    this.TransitNumberField = value;
                    this.RaisePropertyChanged("TransitNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentNotificationResponse", Namespace="FCT.EPS.PaymentTrackingService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PaymentNotificationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool NotificationRecievedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool NotificationRecieved {
            get {
                return this.NotificationRecievedField;
            }
            set {
                if ((this.NotificationRecievedField.Equals(value) != true)) {
                    this.NotificationRecievedField = value;
                    this.RaisePropertyChanged("NotificationRecieved");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceNotAvailableFault", Namespace="https://schemas.firstcdn.com/LawyerIntegration/ExternalInterface/20071214")]
    [System.SerializableAttribute()]
    public partial class ServiceNotAvailableFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavigateToUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.ErrorCode ErrorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string NavigateToUrl {
            get {
                return this.NavigateToUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.NavigateToUrlField, value) != true)) {
                    this.NavigateToUrlField = value;
                    this.RaisePropertyChanged("NavigateToUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.ErrorCode ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorCode", Namespace="FCT.LLC.Common.DataContracts")]
    public enum ErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DealDoesNotExist = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DealsDoNotMatch = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisbursementsNotFound = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DisbursementsDoNotMatch = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoTrustAccountID = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TrustAccountNotActive = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SummaryNotFound = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FundsDoNotMatch = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PurchaserHasNotSigned = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VendorHasNotSigned = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CPASystemClosure = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VendorLawyerDisbursementNotFound = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VendorLawyerAmountInadequate = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weekend = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotWithinWorkingHours = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SubmitPaymentFaulted = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InSufficientFunds = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VendorAcknowledged = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InactiveUser = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OutstandingDeposit = 20,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentTrackingServiceReference.IPaymentTrackingService")]
    public interface IPaymentTrackingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentTrackingService/NotifyPaymentConfirmation", ReplyAction="http://tempuri.org/IPaymentTrackingService/NotifyPaymentConfirmationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.ServiceNotAvailableFault), Action="http://tempuri.org/IPaymentTrackingService/NotifyPaymentConfirmationServiceNotAva" +
            "ilableFaultFault", Name="ServiceNotAvailableFault", Namespace="https://schemas.firstcdn.com/LawyerIntegration/ExternalInterface/20071214")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.PaymentNotificationResponse NotifyPaymentConfirmation(FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.PaymentNotificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentTrackingService/NotifyPaymentConfirmation", ReplyAction="http://tempuri.org/IPaymentTrackingService/NotifyPaymentConfirmationResponse")]
        System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.PaymentNotificationResponse> NotifyPaymentConfirmationAsync(FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.PaymentNotificationRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentTrackingServiceChannel : FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.IPaymentTrackingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentTrackingServiceClient : System.ServiceModel.ClientBase<FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.IPaymentTrackingService>, FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.IPaymentTrackingService {
        
        public PaymentTrackingServiceClient() {
        }
        
        public PaymentTrackingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentTrackingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentTrackingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentTrackingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.PaymentNotificationResponse NotifyPaymentConfirmation(FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.PaymentNotificationRequest request) {
            return base.Channel.NotifyPaymentConfirmation(request);
        }
        
        public System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.PaymentNotificationResponse> NotifyPaymentConfirmationAsync(FCT.EPS.WSP.ExternalResources.PaymentTrackingServiceReference.PaymentNotificationRequest request) {
            return base.Channel.NotifyPaymentConfirmationAsync(request);
        }
    }
}
