//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.EPS.WSP.ExternalResources.FinanceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ChequeRequestList", Namespace="FCT.EPS.FinanceService.DataContracts", ItemName="ChequeRequestDetail")]
    [System.SerializableAttribute()]
    public class ChequeRequestList : System.Collections.Generic.List<FCT.EPS.WSP.ExternalResources.FinanceService.ChequeRequest> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChequeRequest", Namespace="FCT.EPS.FinanceService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ChequeRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FCTRefNumField;
        
        private int ProgramIDField;
        
        private int DisbursementTransactionIDField;
        
        private string ServiceDescriptionField;
        
        private int StatusIDField;
        
        private string PayeeNameField;
        
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine5Field;
        
        private decimal AmountField;
        
        private System.DateTime DateEnteredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string FCTRefNum {
            get {
                return this.FCTRefNumField;
            }
            set {
                if ((object.ReferenceEquals(this.FCTRefNumField, value) != true)) {
                    this.FCTRefNumField = value;
                    this.RaisePropertyChanged("FCTRefNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProgramID {
            get {
                return this.ProgramIDField;
            }
            set {
                if ((this.ProgramIDField.Equals(value) != true)) {
                    this.ProgramIDField = value;
                    this.RaisePropertyChanged("ProgramID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DisbursementTransactionID {
            get {
                return this.DisbursementTransactionIDField;
            }
            set {
                if ((this.DisbursementTransactionIDField.Equals(value) != true)) {
                    this.DisbursementTransactionIDField = value;
                    this.RaisePropertyChanged("DisbursementTransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string ServiceDescription {
            get {
                return this.ServiceDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceDescriptionField, value) != true)) {
                    this.ServiceDescriptionField = value;
                    this.RaisePropertyChanged("ServiceDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string PayeeName {
            get {
                return this.PayeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PayeeNameField, value) != true)) {
                    this.PayeeNameField = value;
                    this.RaisePropertyChanged("PayeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string AddressLine3 {
            get {
                return this.AddressLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine3Field, value) != true)) {
                    this.AddressLine3Field = value;
                    this.RaisePropertyChanged("AddressLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string AddressLine4 {
            get {
                return this.AddressLine4Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine4Field, value) != true)) {
                    this.AddressLine4Field = value;
                    this.RaisePropertyChanged("AddressLine4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string AddressLine5 {
            get {
                return this.AddressLine5Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine5Field, value) != true)) {
                    this.AddressLine5Field = value;
                    this.RaisePropertyChanged("AddressLine5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.DateTime DateEntered {
            get {
                return this.DateEnteredField;
            }
            set {
                if ((this.DateEnteredField.Equals(value) != true)) {
                    this.DateEnteredField = value;
                    this.RaisePropertyChanged("DateEntered");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="FCT.EPS.FinanceService.FaultContracts")]
    [System.SerializableAttribute()]
    public partial class ServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChequeStatusRequest", Namespace="FCT.EPS.FinanceService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ChequeStatusRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EPSChequeRequestIDField;
        
        private int NumberOfRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EPSChequeRequestID {
            get {
                return this.EPSChequeRequestIDField;
            }
            set {
                if ((this.EPSChequeRequestIDField.Equals(value) != true)) {
                    this.EPSChequeRequestIDField = value;
                    this.RaisePropertyChanged("EPSChequeRequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumberOfRecords {
            get {
                return this.NumberOfRecordsField;
            }
            set {
                if ((this.NumberOfRecordsField.Equals(value) != true)) {
                    this.NumberOfRecordsField = value;
                    this.RaisePropertyChanged("NumberOfRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ChequeStatusResponseList", Namespace="FCT.EPS.FinanceService.DataContracts", ItemName="ChequeStatus")]
    [System.SerializableAttribute()]
    public class ChequeStatusResponseList : System.Collections.Generic.List<FCT.EPS.WSP.ExternalResources.FinanceService.ChequeStatusResponse> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChequeStatusResponse", Namespace="FCT.EPS.FinanceService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ChequeStatusResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EPSChequeRequestIDField;
        
        private string FCTRefNumField;
        
        private int DisbursemenTransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChequeNumberField;
        
        private int StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatePaidField;
        
        private string PaymentBatchIDField;
        
        private string PaymentBatchDescriptionField;
        
        private System.DateTime LastModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EPSChequeRequestID {
            get {
                return this.EPSChequeRequestIDField;
            }
            set {
                if ((this.EPSChequeRequestIDField.Equals(value) != true)) {
                    this.EPSChequeRequestIDField = value;
                    this.RaisePropertyChanged("EPSChequeRequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string FCTRefNum {
            get {
                return this.FCTRefNumField;
            }
            set {
                if ((object.ReferenceEquals(this.FCTRefNumField, value) != true)) {
                    this.FCTRefNumField = value;
                    this.RaisePropertyChanged("FCTRefNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DisbursemenTransactionID {
            get {
                return this.DisbursemenTransactionIDField;
            }
            set {
                if ((this.DisbursemenTransactionIDField.Equals(value) != true)) {
                    this.DisbursemenTransactionIDField = value;
                    this.RaisePropertyChanged("DisbursemenTransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ChequeNumber {
            get {
                return this.ChequeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ChequeNumberField, value) != true)) {
                    this.ChequeNumberField = value;
                    this.RaisePropertyChanged("ChequeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> DatePaid {
            get {
                return this.DatePaidField;
            }
            set {
                if ((this.DatePaidField.Equals(value) != true)) {
                    this.DatePaidField = value;
                    this.RaisePropertyChanged("DatePaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string PaymentBatchID {
            get {
                return this.PaymentBatchIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentBatchIDField, value) != true)) {
                    this.PaymentBatchIDField = value;
                    this.RaisePropertyChanged("PaymentBatchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string PaymentBatchDescription {
            get {
                return this.PaymentBatchDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentBatchDescriptionField, value) != true)) {
                    this.PaymentBatchDescriptionField = value;
                    this.RaisePropertyChanged("PaymentBatchDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime LastModifiedDate {
            get {
                return this.LastModifiedDateField;
            }
            set {
                if ((this.LastModifiedDateField.Equals(value) != true)) {
                    this.LastModifiedDateField = value;
                    this.RaisePropertyChanged("LastModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FCTFeeSummaryRequestList", Namespace="FCT.EPS.FinanceService.DataContracts", ItemName="FCTFeeSummaryRequest")]
    [System.SerializableAttribute()]
    public class FCTFeeSummaryRequestList : System.Collections.Generic.List<FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeSummary> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FCTFeeSummary", Namespace="FCT.EPS.FinanceService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class FCTFeeSummary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FCTRefNumberField;
        
        private int ProgramIDField;
        
        private int DisbursementTransactionIDField;
        
        private int ServiceField;
        
        private string PayeeNameField;
        
        private string BillingPartyID1Field;
        
        private int BillingPartyID2Field;
        
        private string ProvinceCodeField;
        
        private decimal AmountField;
        
        private decimal PSTField;
        
        private decimal GSTField;
        
        private decimal HSTField;
        
        private decimal QSTField;
        
        private decimal RSTField;
        
        private decimal TotalFeeField;
        
        private System.DateTime DateEnteredField;
        
        private int ServiceBatchIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string FCTRefNumber {
            get {
                return this.FCTRefNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FCTRefNumberField, value) != true)) {
                    this.FCTRefNumberField = value;
                    this.RaisePropertyChanged("FCTRefNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProgramID {
            get {
                return this.ProgramIDField;
            }
            set {
                if ((this.ProgramIDField.Equals(value) != true)) {
                    this.ProgramIDField = value;
                    this.RaisePropertyChanged("ProgramID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DisbursementTransactionID {
            get {
                return this.DisbursementTransactionIDField;
            }
            set {
                if ((this.DisbursementTransactionIDField.Equals(value) != true)) {
                    this.DisbursementTransactionIDField = value;
                    this.RaisePropertyChanged("DisbursementTransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((this.ServiceField.Equals(value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string PayeeName {
            get {
                return this.PayeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PayeeNameField, value) != true)) {
                    this.PayeeNameField = value;
                    this.RaisePropertyChanged("PayeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string BillingPartyID1 {
            get {
                return this.BillingPartyID1Field;
            }
            set {
                if ((object.ReferenceEquals(this.BillingPartyID1Field, value) != true)) {
                    this.BillingPartyID1Field = value;
                    this.RaisePropertyChanged("BillingPartyID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int BillingPartyID2 {
            get {
                return this.BillingPartyID2Field;
            }
            set {
                if ((this.BillingPartyID2Field.Equals(value) != true)) {
                    this.BillingPartyID2Field = value;
                    this.RaisePropertyChanged("BillingPartyID2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string ProvinceCode {
            get {
                return this.ProvinceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceCodeField, value) != true)) {
                    this.ProvinceCodeField = value;
                    this.RaisePropertyChanged("ProvinceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public decimal PST {
            get {
                return this.PSTField;
            }
            set {
                if ((this.PSTField.Equals(value) != true)) {
                    this.PSTField = value;
                    this.RaisePropertyChanged("PST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal GST {
            get {
                return this.GSTField;
            }
            set {
                if ((this.GSTField.Equals(value) != true)) {
                    this.GSTField = value;
                    this.RaisePropertyChanged("GST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public decimal HST {
            get {
                return this.HSTField;
            }
            set {
                if ((this.HSTField.Equals(value) != true)) {
                    this.HSTField = value;
                    this.RaisePropertyChanged("HST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public decimal QST {
            get {
                return this.QSTField;
            }
            set {
                if ((this.QSTField.Equals(value) != true)) {
                    this.QSTField = value;
                    this.RaisePropertyChanged("QST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public decimal RST {
            get {
                return this.RSTField;
            }
            set {
                if ((this.RSTField.Equals(value) != true)) {
                    this.RSTField = value;
                    this.RaisePropertyChanged("RST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public decimal TotalFee {
            get {
                return this.TotalFeeField;
            }
            set {
                if ((this.TotalFeeField.Equals(value) != true)) {
                    this.TotalFeeField = value;
                    this.RaisePropertyChanged("TotalFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.DateTime DateEntered {
            get {
                return this.DateEnteredField;
            }
            set {
                if ((this.DateEnteredField.Equals(value) != true)) {
                    this.DateEnteredField = value;
                    this.RaisePropertyChanged("DateEntered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public int ServiceBatchID {
            get {
                return this.ServiceBatchIDField;
            }
            set {
                if ((this.ServiceBatchIDField.Equals(value) != true)) {
                    this.ServiceBatchIDField = value;
                    this.RaisePropertyChanged("ServiceBatchID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FCTFeeStatusRequest", Namespace="FCT.EPS.FinanceService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class FCTFeeStatusRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EPSFCTFeeSummaryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EPSFCTFeeSummaryID {
            get {
                return this.EPSFCTFeeSummaryIDField;
            }
            set {
                if ((this.EPSFCTFeeSummaryIDField.Equals(value) != true)) {
                    this.EPSFCTFeeSummaryIDField = value;
                    this.RaisePropertyChanged("EPSFCTFeeSummaryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfRecords {
            get {
                return this.NumberOfRecordsField;
            }
            set {
                if ((this.NumberOfRecordsField.Equals(value) != true)) {
                    this.NumberOfRecordsField = value;
                    this.RaisePropertyChanged("NumberOfRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FCTFeeStatusResponse", Namespace="FCT.EPS.FinanceService.DataContracts", ItemName="FCTFeeStatusList")]
    [System.SerializableAttribute()]
    public class FCTFeeStatusResponse : System.Collections.Generic.List<FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeStatusInfo> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FCTFeeStatusInfo", Namespace="FCT.EPS.FinanceService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class FCTFeeStatusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EPSFCTFeeSummaryIDField;
        
        private string FCTRefNumField;
        
        private int ServiceBatchIDField;
        
        private int DisbursemenTransactionIDField;
        
        private string JournalControlNumberField;
        
        private int ProcessFlagField;
        
        private int ErrorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatePaidField;
        
        private System.DateTime LastModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EPSFCTFeeSummaryID {
            get {
                return this.EPSFCTFeeSummaryIDField;
            }
            set {
                if ((this.EPSFCTFeeSummaryIDField.Equals(value) != true)) {
                    this.EPSFCTFeeSummaryIDField = value;
                    this.RaisePropertyChanged("EPSFCTFeeSummaryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string FCTRefNum {
            get {
                return this.FCTRefNumField;
            }
            set {
                if ((object.ReferenceEquals(this.FCTRefNumField, value) != true)) {
                    this.FCTRefNumField = value;
                    this.RaisePropertyChanged("FCTRefNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ServiceBatchID {
            get {
                return this.ServiceBatchIDField;
            }
            set {
                if ((this.ServiceBatchIDField.Equals(value) != true)) {
                    this.ServiceBatchIDField = value;
                    this.RaisePropertyChanged("ServiceBatchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DisbursemenTransactionID {
            get {
                return this.DisbursemenTransactionIDField;
            }
            set {
                if ((this.DisbursemenTransactionIDField.Equals(value) != true)) {
                    this.DisbursemenTransactionIDField = value;
                    this.RaisePropertyChanged("DisbursemenTransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string JournalControlNumber {
            get {
                return this.JournalControlNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.JournalControlNumberField, value) != true)) {
                    this.JournalControlNumberField = value;
                    this.RaisePropertyChanged("JournalControlNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int ProcessFlag {
            get {
                return this.ProcessFlagField;
            }
            set {
                if ((this.ProcessFlagField.Equals(value) != true)) {
                    this.ProcessFlagField = value;
                    this.RaisePropertyChanged("ProcessFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int ErrorNumber {
            get {
                return this.ErrorNumberField;
            }
            set {
                if ((this.ErrorNumberField.Equals(value) != true)) {
                    this.ErrorNumberField = value;
                    this.RaisePropertyChanged("ErrorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<System.DateTime> DatePaid {
            get {
                return this.DatePaidField;
            }
            set {
                if ((this.DatePaidField.Equals(value) != true)) {
                    this.DatePaidField = value;
                    this.RaisePropertyChanged("DatePaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime LastModifiedDate {
            get {
                return this.LastModifiedDateField;
            }
            set {
                if ((this.LastModifiedDateField.Equals(value) != true)) {
                    this.LastModifiedDateField = value;
                    this.RaisePropertyChanged("LastModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FinanceService.IFinanceService")]
    public interface IFinanceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/CreateCheques", ReplyAction="http://tempuri.org/IFinanceService/CreateChequesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FCT.EPS.WSP.ExternalResources.FinanceService.ServiceFault), Action="http://tempuri.org/IFinanceService/CreateChequesServiceFaultFault", Name="ServiceFault", Namespace="FCT.EPS.FinanceService.FaultContracts")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        bool CreateCheques(FCT.EPS.WSP.ExternalResources.FinanceService.ChequeRequestList ListOfCheques);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/CreateCheques", ReplyAction="http://tempuri.org/IFinanceService/CreateChequesResponse")]
        System.Threading.Tasks.Task<bool> CreateChequesAsync(FCT.EPS.WSP.ExternalResources.FinanceService.ChequeRequestList ListOfCheques);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/GetListOfUpdatedCheques", ReplyAction="http://tempuri.org/IFinanceService/GetListOfUpdatedChequesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FCT.EPS.WSP.ExternalResources.FinanceService.ServiceFault), Action="http://tempuri.org/IFinanceService/GetListOfUpdatedChequesServiceFaultFault", Name="ServiceFault", Namespace="FCT.EPS.FinanceService.FaultContracts")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        FCT.EPS.WSP.ExternalResources.FinanceService.ChequeStatusResponseList GetListOfUpdatedCheques(FCT.EPS.WSP.ExternalResources.FinanceService.ChequeStatusRequest chequeStatusRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/GetListOfUpdatedCheques", ReplyAction="http://tempuri.org/IFinanceService/GetListOfUpdatedChequesResponse")]
        System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.FinanceService.ChequeStatusResponseList> GetListOfUpdatedChequesAsync(FCT.EPS.WSP.ExternalResources.FinanceService.ChequeStatusRequest chequeStatusRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/CreateFees", ReplyAction="http://tempuri.org/IFinanceService/CreateFeesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FCT.EPS.WSP.ExternalResources.FinanceService.ServiceFault), Action="http://tempuri.org/IFinanceService/CreateFeesServiceFaultFault", Name="ServiceFault", Namespace="FCT.EPS.FinanceService.FaultContracts")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        bool CreateFees(FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeSummaryRequestList ListOfFees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/CreateFees", ReplyAction="http://tempuri.org/IFinanceService/CreateFeesResponse")]
        System.Threading.Tasks.Task<bool> CreateFeesAsync(FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeSummaryRequestList ListOfFees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/GetFCTFeeStatus", ReplyAction="http://tempuri.org/IFinanceService/GetFCTFeeStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(FCT.EPS.WSP.ExternalResources.FinanceService.ServiceFault), Action="http://tempuri.org/IFinanceService/GetFCTFeeStatusServiceFaultFault", Name="ServiceFault", Namespace="FCT.EPS.FinanceService.FaultContracts")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeStatusResponse GetFCTFeeStatus(FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeStatusRequest feeStatusRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceService/GetFCTFeeStatus", ReplyAction="http://tempuri.org/IFinanceService/GetFCTFeeStatusResponse")]
        System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeStatusResponse> GetFCTFeeStatusAsync(FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeStatusRequest feeStatusRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinanceServiceChannel : FCT.EPS.WSP.ExternalResources.FinanceService.IFinanceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinanceServiceClient : System.ServiceModel.ClientBase<FCT.EPS.WSP.ExternalResources.FinanceService.IFinanceService>, FCT.EPS.WSP.ExternalResources.FinanceService.IFinanceService {
        
        public FinanceServiceClient() {
        }
        
        public FinanceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinanceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateCheques(FCT.EPS.WSP.ExternalResources.FinanceService.ChequeRequestList ListOfCheques) {
            return base.Channel.CreateCheques(ListOfCheques);
        }
        
        public System.Threading.Tasks.Task<bool> CreateChequesAsync(FCT.EPS.WSP.ExternalResources.FinanceService.ChequeRequestList ListOfCheques) {
            return base.Channel.CreateChequesAsync(ListOfCheques);
        }
        
        public FCT.EPS.WSP.ExternalResources.FinanceService.ChequeStatusResponseList GetListOfUpdatedCheques(FCT.EPS.WSP.ExternalResources.FinanceService.ChequeStatusRequest chequeStatusRequest) {
            return base.Channel.GetListOfUpdatedCheques(chequeStatusRequest);
        }
        
        public System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.FinanceService.ChequeStatusResponseList> GetListOfUpdatedChequesAsync(FCT.EPS.WSP.ExternalResources.FinanceService.ChequeStatusRequest chequeStatusRequest) {
            return base.Channel.GetListOfUpdatedChequesAsync(chequeStatusRequest);
        }
        
        public bool CreateFees(FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeSummaryRequestList ListOfFees) {
            return base.Channel.CreateFees(ListOfFees);
        }
        
        public System.Threading.Tasks.Task<bool> CreateFeesAsync(FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeSummaryRequestList ListOfFees) {
            return base.Channel.CreateFeesAsync(ListOfFees);
        }
        
        public FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeStatusResponse GetFCTFeeStatus(FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeStatusRequest feeStatusRequest) {
            return base.Channel.GetFCTFeeStatus(feeStatusRequest);
        }
        
        public System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeStatusResponse> GetFCTFeeStatusAsync(FCT.EPS.WSP.ExternalResources.FinanceService.FCTFeeStatusRequest feeStatusRequest) {
            return base.Channel.GetFCTFeeStatusAsync(feeStatusRequest);
        }
    }
}
