//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using FCT.LLC.Common.DataContracts;
using WcfSerialization = global::System.Runtime.Serialization;

namespace FCT.LLC.BusinessService.Contracts.FaultContracts
{
	/// <summary>
	/// Data Contract Class - ConcurrencyViolationFault
	/// </summary>
    [WcfSerialization::DataContract(Namespace = "FCT.LLC.BusinessService.Contracts.FaultContracts", Name = "ConcurrencyViolationFault")]
	public partial class ConcurrencyViolationFault 
	{
		private string request;
		private string description;
	    private ErrorCode violationCode;
		
		[WcfSerialization::DataMember(Name = "Request", IsRequired = false, Order = 0)]
		public string Request
		{
		  get { return request; }
		  set { request = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Description", IsRequired = false, Order = 1)]
		public string Description
		{
		  get { return description; }
		  set { description = value; }
		}

        [WcfSerialization::DataMember(Name = "ViolationCode", IsRequired = false, Order = 2)]
        public ErrorCode ViolationCode
        {
            get { return violationCode; }
            set { violationCode = value; }
        }	
	}
}

