//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.EPS.WSP.GCLA.Implementation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06:00:00")]
        public global::System.TimeSpan pollStart {
            get {
                return ((global::System.TimeSpan)(this["pollStart"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600000")]
        public int GetElectronicPollingIntervalInMilliSeconds {
            get {
                return ((int)(this["GetElectronicPollingIntervalInMilliSeconds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The Creditor {0} [ID={1}] was received in today\'s the listing dated {2} with the " +
            "disable rule . Please action accordingly.")]
        public string mailBodyDel {
            get {
                return ((string)(this["mailBodyDel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int maxRetryNumber {
            get {
                return ((int)(this["maxRetryNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\wrkdir\\EASYFUND\\FCT\\RBCBPS\\Archive\\Reception")]
        public string pathToArcCCListFile {
            get {
                return ((string)(this["pathToArcCCListFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dateShift {
            get {
                return ((int)(this["dateShift"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0:ddd-MM-yyyy}")]
        public string mailDateFormat {
            get {
                return ((string)(this["mailDateFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\wrkdir\\EASYFUND\\FCT\\RBCBPS\\Archive\\Report")]
        public string pathToReport {
            get {
                return ((string)(this["pathToReport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\wrkdir\\EASYFUND\\FCT\\RBCBPS\\Reception\\CCLISTA.*")]
        public string pathToCCListFile1 {
            get {
                return ((string)(this["pathToCCListFile1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\wrkdir\\EASYFUND\\FCT\\RBCBPS\\Archive\\Reception")]
        public string pathToArcCCListFile1 {
            get {
                return ((string)(this["pathToArcCCListFile1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dateShift1 {
            get {
                return ((int)(this["dateShift1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RBC CC List has Error(s) - {0}. ")]
        public string mailSubjectErr {
            get {
                return ((string)(this["mailSubjectErr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EasyFundSupport@fct.ca")]
        public string mailTo {
            get {
                return ((string)(this["mailTo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RBC CC List has New Creditor(s) - {0:ddd-MM-yyyy}")]
        public string mailSubjectNew {
            get {
                return ((string)(this["mailSubjectNew"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Creditor found in RBC Creditor List dated {0} with new Disable rule. ")]
        public string mailSubjectDel {
            get {
                return ((string)(this["mailSubjectDel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The following new corporate creditors were added on {0:ddd-MM-yyyy}: {1}\r\n\r\nPleas" +
            "e action accordingly.")]
        public string mailBodyNew {
            get {
                return ((string)(this["mailBodyNew"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int retryInterval {
            get {
                return ((int)(this["retryInterval"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\wrkdir\\EASYFUND\\FCT\\RBCBPS\\Reception\\CCLISTA.*")]
        public string pathToCCListFile {
            get {
                return ((string)(this["pathToCCListFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\wrkdir\\EASYFUND\\FCT\\RBCBPS\\Archive\\Reception")]
        public string pathToErrCCListFile {
            get {
                return ((string)(this["pathToErrCCListFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The following corporate creditors were not processed owing to errors on {0} : \r\n " +
            "         {1}.\r\n          \r\n          Please action accordingly.")]
        public string mailBodyErr {
            get {
                return ((string)(this["mailBodyErr"]));
            }
        }
    }
}
