//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2300
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.2300.
// 
using System.Xml.Serialization;

[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public class ScreenWithCustomerData
{
    /// <remarks/>
    public ScreenWithCustomerData()
    {
        SysServRequest = new ScreenSysServRequestWithCustomerData();
    }

    /// <remarks/>
    public ScreenSysServRequestWithCustomerData SysServRequest;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ErrNumber = "0";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ErrDesc = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Action = "HELP";
}


/// <remarks/>
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public class Screen 
{
	/// <remarks/>
	public Screen()
	{
		SysServRequest = new ScreenSysServRequest();
	}
    
	/// <remarks/>
	public ScreenSysServRequest SysServRequest;
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string ErrNumber = "0";
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string ErrDesc = "";
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Action = "HELP";
}

/// <remarks/>
public class ScreenSysServRequest 
{
    /// <remarks/>
	public ScreenSysServRequest()
	{
		Document = new ScreenSysServRequestDocument();
		Destination = new ScreenSysServRequestDestination();
	}

	/// <remarks/>
    public string Application = "LLC";
    
	/// <remarks/>
	public string RequestorID = "";
    
	/// <remarks/>
	public string DealID = "";
    
	/// <remarks/>
	public ScreenSysServRequestDocument Document;
    
	/// <remarks/>
	public ScreenSysServRequestDestination Destination;
}


/// <remarks/>
public class ScreenSysServRequestWithCustomerData
{
    /// <remarks/>
    public ScreenSysServRequestWithCustomerData()
    {
        Document = new ScreenSysServRequestDocumentWithCustomerData();
        Destination = new ScreenSysServRequestDestination();
    }

    /// <remarks/>
    public string Application = "LLC";

    /// <remarks/>
    public string RequestorID = "";

    /// <remarks/>
    public string DealID = "";

    /// <remarks/>
    public ScreenSysServRequestDocumentWithCustomerData Document;

    /// <remarks/>
    public ScreenSysServRequestDestination Destination;
}
/// <remarks/>
public class ScreenSysServRequestDocument 
{
    /// <remarks/>
	public ScreenSysServRequestDocument()
	{
       
            DocumentData = new ScreenSysServRequestDocumentDocumentData();
        

	}

	/// <remarks/>
	public ScreenSysServRequestDocumentDocumentData DocumentData;


	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string DocType = "NONE";
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string SourceURL = "";
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string InfoSource = "NONE";
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string ModelDocument = "NONE";
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string ConvertToPDF = "False";

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string ConvertToText = "False";
}

public class ScreenSysServRequestDocumentWithCustomerData
{
    /// <remarks/>
    public ScreenSysServRequestDocumentWithCustomerData()
    {

        DocumentData = new ScreenSysServRequestDocumentDocumentDataWithCustomerData();


    }

    /// <remarks/>
    public ScreenSysServRequestDocumentDocumentDataWithCustomerData DocumentData;


    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DocType = "NONE";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SourceURL = "";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string InfoSource = "NONE";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ModelDocument = "NONE";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ConvertToPDF = "False";

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ConvertToText = "False";
}



public class ScreenSysServRequestDocumentDocumentData
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DealId", IsNullable = false)]
    public ScreenSysServRequestDocumentDocumentDataDealId DealId;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentId", IsNullable = false)]
    public ScreenSysServRequestDocumentDocumentDataDocumentID DocumentId;



}

public class ScreenSysServRequestDocumentDocumentDataWithCustomerData
{

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DealId", IsNullable = true)]
    public ScreenSysServRequestDocumentDocumentDataDealId DealId;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentId", IsNullable = true)]
    public ScreenSysServRequestDocumentDocumentDataDocumentID DocumentId;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CustomerID", IsNullable = true)]
    public ScreenSysServRequestDocumentDocumentDataCustomerId CustomerId;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PolicyID", IsNullable = true)]
    public ScreenSysServRequestDocumentDocumentDataPolicyId PolicyId;
}
/// <remarks/>
public class ScreenSysServRequestDocumentDocumentDataDealId
{
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string DataType ;
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value;
}

/// <remarks/>
public class ScreenSysServRequestDestinationMethodsLIST 
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DMSPath;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Versions;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ListArchive;
}

/// <remarks/>
public class ScreenSysServRequestDestinationMethodsCONVERT 
{
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string SourceURL;
}

/// <remarks/>
public class ScreenSysServRequestDestinationMethodsRETRIEVE 
{
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string DMSPath;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Version;
}

/// <remarks/>
public class ScreenSysServRequestDestinationMethodsERASE
{
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string DMSPath;
}

/// <remarks/>
public class ScreenSysServRequestDestinationMethodsSTOREAttributes 
{
    
	/// <remarks/>
	public string Category;
    
	/// <remarks/>
	public string UserID;
	
	/// <remarks/>
	public string ReportInstanceID;

	/// <remarks/>
	public string Description;

	/// <remarks/>
	public string RetrievedDate;

	/// <remarks/>
	public string DocumentCode;

	/// <remarks/>
	public string Format;

	/// <remarks/>
	public string FCTURN;

	//
	// Add more attributes here as required!!!!
	//
}

/// <remarks/>
public class ScreenSysServRequestDestinationMethodsSTORE 
{
    
	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("Attributes")]
	public ScreenSysServRequestDestinationMethodsSTOREAttributes[] Attributes;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string DMSPath;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Priority = "Low";
}

/// <remarks/>
public class ScreenSysServRequestDestinationMethodsBNET 
{
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string EmailAddress;
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Subject;
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Message;
}


/// <remarks/>
public class ScreenSysServRequestDestinationMethodsPRINT
{
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Device ;
}
/// <remarks/>
public class ScreenSysServRequestDestinationMethodsFAX 
{
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string FaxNumber;
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Message;
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string CoverPage;
}

/// <remarks/>
public class ScreenSysServRequestDestinationMethodsEMAIL 
{

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string EmailAddress;
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Subject;
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string Message;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string TXT;

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string NoAttachment = "True";
}

/// <remarks/>
public class ScreenSysServRequestDestinationMethods 
{
    
	/// <remarks/>
	public string VIEW;
    
	/// <remarks/>
	public ScreenSysServRequestDestinationMethodsEMAIL EMAIL;
    
	/// <remarks/>
	public ScreenSysServRequestDestinationMethodsFAX FAX;
    
	/// <remarks/>
	public ScreenSysServRequestDestinationMethodsBNET BNET;
    
	/// <remarks/>
	public ScreenSysServRequestDestinationMethodsSTORE STORE;
    
	/// <remarks/>
	public ScreenSysServRequestDestinationMethodsRETRIEVE RETRIEVE;
    
	/// <remarks/>
	public ScreenSysServRequestDestinationMethodsCONVERT CONVERT;
    
	/// <remarks/>
	public ScreenSysServRequestDestinationMethodsLIST LIST;

	/// <remarks/>
	public ScreenSysServRequestDestinationMethodsERASE ERASE;

    /// <remarks/>
    public ScreenSysServRequestDestinationMethodsPRINT PRINT;
}

/// <remarks/>
public class ScreenSysServRequestDestination 
{
    /// <remarks/>
	public ScreenSysServRequestDestination()
	{
		Methods = new ScreenSysServRequestDestinationMethods();
	}

	/// <remarks/>
	public ScreenSysServRequestDestinationMethods Methods;
}



/// <remarks/>
public class ScreenSysServRequestDocumentDocumentDataDocumentID 
{
    
	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string DataType;
    
	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	public string Value;
}

/// <remarks/>
public class ScreenSysServRequestDocumentDocumentDataCustomerId
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DataType;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}

public class ScreenSysServRequestDocumentDocumentDataPolicyId
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DataType;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value;
}