//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCT.EPS.WSP.ExternalResources.SystemService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request", ConfigurationName="SystemService.RequestSoap")]
    public interface RequestSoap {
        
        // CODEGEN: Generating message contract since element name RequestXML from namespace http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request/Submit", ReplyAction="*")]
        FCT.EPS.WSP.ExternalResources.SystemService.SubmitResponse Submit(FCT.EPS.WSP.ExternalResources.SystemService.SubmitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request/Submit", ReplyAction="*")]
        System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.SystemService.SubmitResponse> SubmitAsync(FCT.EPS.WSP.ExternalResources.SystemService.SubmitRequest request);
        
        // CODEGEN: Generating message contract since element name RequestXML from namespace http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request/QuerySt" +
            "atus", ReplyAction="*")]
        FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusResponse QueryStatus(FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request/QuerySt" +
            "atus", ReplyAction="*")]
        System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusResponse> QueryStatusAsync(FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusRequest request);
        
        // CODEGEN: Generating message contract since element name PingResult from namespace http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request/Ping", ReplyAction="*")]
        FCT.EPS.WSP.ExternalResources.SystemService.PingResponse Ping(FCT.EPS.WSP.ExternalResources.SystemService.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request/Ping", ReplyAction="*")]
        System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.SystemService.PingResponse> PingAsync(FCT.EPS.WSP.ExternalResources.SystemService.PingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Submit", Namespace="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request", Order=0)]
        public FCT.EPS.WSP.ExternalResources.SystemService.SubmitRequestBody Body;
        
        public SubmitRequest() {
        }
        
        public SubmitRequest(FCT.EPS.WSP.ExternalResources.SystemService.SubmitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request")]
    public partial class SubmitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestXML;
        
        public SubmitRequestBody() {
        }
        
        public SubmitRequestBody(string RequestXML) {
            this.RequestXML = RequestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitResponse", Namespace="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request", Order=0)]
        public FCT.EPS.WSP.ExternalResources.SystemService.SubmitResponseBody Body;
        
        public SubmitResponse() {
        }
        
        public SubmitResponse(FCT.EPS.WSP.ExternalResources.SystemService.SubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request")]
    public partial class SubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubmitResult;
        
        public SubmitResponseBody() {
        }
        
        public SubmitResponseBody(string SubmitResult) {
            this.SubmitResult = SubmitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryStatus", Namespace="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request", Order=0)]
        public FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusRequestBody Body;
        
        public QueryStatusRequest() {
        }
        
        public QueryStatusRequest(FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request")]
    public partial class QueryStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestXML;
        
        public QueryStatusRequestBody() {
        }
        
        public QueryStatusRequestBody(string RequestXML) {
            this.RequestXML = RequestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryStatusResponse", Namespace="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request", Order=0)]
        public FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusResponseBody Body;
        
        public QueryStatusResponse() {
        }
        
        public QueryStatusResponse(FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request")]
    public partial class QueryStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QueryStatusResult;
        
        public QueryStatusResponseBody() {
        }
        
        public QueryStatusResponseBody(string QueryStatusResult) {
            this.QueryStatusResult = QueryStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ping", Namespace="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request", Order=0)]
        public FCT.EPS.WSP.ExternalResources.SystemService.PingRequestBody Body;
        
        public PingRequest() {
        }
        
        public PingRequest(FCT.EPS.WSP.ExternalResources.SystemService.PingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PingRequestBody {
        
        public PingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingResponse", Namespace="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request", Order=0)]
        public FCT.EPS.WSP.ExternalResources.SystemService.PingResponseBody Body;
        
        public PingResponse() {
        }
        
        public PingResponse(FCT.EPS.WSP.ExternalResources.SystemService.PingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://firstcanadiantitle.ca/DocumentServices/WebSubmissionServer/Request")]
    public partial class PingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PingResult;
        
        public PingResponseBody() {
        }
        
        public PingResponseBody(string PingResult) {
            this.PingResult = PingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RequestSoapChannel : FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestSoapClient : System.ServiceModel.ClientBase<FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap>, FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap {
        
        public RequestSoapClient() {
        }
        
        public RequestSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequestSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FCT.EPS.WSP.ExternalResources.SystemService.SubmitResponse FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap.Submit(FCT.EPS.WSP.ExternalResources.SystemService.SubmitRequest request) {
            return base.Channel.Submit(request);
        }
        
        public string Submit(string RequestXML) {
            FCT.EPS.WSP.ExternalResources.SystemService.SubmitRequest inValue = new FCT.EPS.WSP.ExternalResources.SystemService.SubmitRequest();
            inValue.Body = new FCT.EPS.WSP.ExternalResources.SystemService.SubmitRequestBody();
            inValue.Body.RequestXML = RequestXML;
            FCT.EPS.WSP.ExternalResources.SystemService.SubmitResponse retVal = ((FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap)(this)).Submit(inValue);
            return retVal.Body.SubmitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.SystemService.SubmitResponse> FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap.SubmitAsync(FCT.EPS.WSP.ExternalResources.SystemService.SubmitRequest request) {
            return base.Channel.SubmitAsync(request);
        }
        
        public System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.SystemService.SubmitResponse> SubmitAsync(string RequestXML) {
            FCT.EPS.WSP.ExternalResources.SystemService.SubmitRequest inValue = new FCT.EPS.WSP.ExternalResources.SystemService.SubmitRequest();
            inValue.Body = new FCT.EPS.WSP.ExternalResources.SystemService.SubmitRequestBody();
            inValue.Body.RequestXML = RequestXML;
            return ((FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap)(this)).SubmitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusResponse FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap.QueryStatus(FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusRequest request) {
            return base.Channel.QueryStatus(request);
        }
        
        public string QueryStatus(string RequestXML) {
            FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusRequest inValue = new FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusRequest();
            inValue.Body = new FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusRequestBody();
            inValue.Body.RequestXML = RequestXML;
            FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusResponse retVal = ((FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap)(this)).QueryStatus(inValue);
            return retVal.Body.QueryStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusResponse> FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap.QueryStatusAsync(FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusRequest request) {
            return base.Channel.QueryStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusResponse> QueryStatusAsync(string RequestXML) {
            FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusRequest inValue = new FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusRequest();
            inValue.Body = new FCT.EPS.WSP.ExternalResources.SystemService.QueryStatusRequestBody();
            inValue.Body.RequestXML = RequestXML;
            return ((FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap)(this)).QueryStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FCT.EPS.WSP.ExternalResources.SystemService.PingResponse FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap.Ping(FCT.EPS.WSP.ExternalResources.SystemService.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public string Ping() {
            FCT.EPS.WSP.ExternalResources.SystemService.PingRequest inValue = new FCT.EPS.WSP.ExternalResources.SystemService.PingRequest();
            inValue.Body = new FCT.EPS.WSP.ExternalResources.SystemService.PingRequestBody();
            FCT.EPS.WSP.ExternalResources.SystemService.PingResponse retVal = ((FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap)(this)).Ping(inValue);
            return retVal.Body.PingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.SystemService.PingResponse> FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap.PingAsync(FCT.EPS.WSP.ExternalResources.SystemService.PingRequest request) {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<FCT.EPS.WSP.ExternalResources.SystemService.PingResponse> PingAsync() {
            FCT.EPS.WSP.ExternalResources.SystemService.PingRequest inValue = new FCT.EPS.WSP.ExternalResources.SystemService.PingRequest();
            inValue.Body = new FCT.EPS.WSP.ExternalResources.SystemService.PingRequestBody();
            return ((FCT.EPS.WSP.ExternalResources.SystemService.RequestSoap)(this)).PingAsync(inValue);
        }
    }
}
